"""unimportant

Revision ID: 692a0f32d320
Revises: c2279dd4e666
Create Date: 2023-11-03 14:31:31.192540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692a0f32d320'
down_revision = 'c2279dd4e666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_menu_extras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_menu_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('order_menu_extras_order_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order_menu', ['order_menu_id'], ['id'])
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_menu_extras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_menu_extras_order_id_fkey', 'order_menu', ['order_id'], ['id'])
        batch_op.drop_column('order_menu_id')

    # ### end Alembic commands ###
